= HC-SR04 Library for Arduino =

It only works with the HC-SR04 sensor with an accuracy of 2CM to 4M. Only digital ports. In instantiation, the first parameter is the Trig pin and the second is the Echo pin. To get the distance in meters use the method getDistanceM without parameters and the distance in centimeters use the method getDistanceCM also without parameters. getDistanceM returns float and getDistanceCM returns int

For more information about this library please visit us at
https://github.com/GuiTurati/HC-SR04.git

=== Reference ===

== Include ==
#include "HC-SR04.h"

== Instance ==
HC-SR04 sensor(byte pinTrig, byte pinEcho);

== Methods ==
float getDistanceM();
	//Returns Distance in Meters
	Parameters:
	- none:
	Return:
	- Distance in Meters (float)
	
int getDistanceM();
	//Returns Distance in Centimeters
	Parameters:
	- none:
	Return:
	- Distance in Centimeters (int)
	
	

== License ==

Copyright (c) 2010 Arduino LLC. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
